### ISSUE TITLE
Add Results Nokia 5.3

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/xOPS-App#1]
Nokia 5.3
(TA-1234)
2020, Snapdragon 665, 4/64GB
(Android 10)

![xOPS](https://user-images.githubusercontent.com/36500228/89885061-23987d80-dbd3-11ea-8ecd-fc114530b9c7.png)

**Comment by KovalevArtem** [comment]
![Screenshot_20200820-002637](https://user-images.githubusercontent.com/36500228/90763063-b8dff400-e2ee-11ea-936d-df1e724b1488.png)

**Comment by maxim-saplin** [comment]
Добавил результаты. Прошу прощения, что долго не отвечал, события в Беларуси выбили из колеи
