### ISSUE TITLE
Add Results LeEco Le 2

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/xOPS-App#10]
**Model:** X527
**Year:** 2016
**CPU:** Qualcomm Snapdragon 652 (MSM8976)

**API:** 23
**System:** Android 6.0.1, EUI 5.8.019S
**Program version:** xOPS 1.1.3

![Screenshot_20210617-035425](https://user-images.githubusercontent.com/36500228/122615692-98f59a00-d091-11eb-985d-b539976e661a.jpg)
![xOPS](https://user-images.githubusercontent.com/36500228/122615696-9bf08a80-d091-11eb-91bb-5742095963d5.png)

**Comment by maxim-saplin** [comment]
Спасибо!
