### ISSUE TITLE
Add Results Sony Xperia XZ2

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/xOPS-App#11]
**Model:** H8266
**Year:** 2018
**CPU:** Qualcomm Snapdragon 845

**API:** 29
**System:** Android 10, 52.1.A.3.49
**Program version:** xOPS 1.1.3

![Screenshot_20210623-223925](https://user-images.githubusercontent.com/36500228/123520969-59940280-d6bc-11eb-8a95-0f27b6d30ee3.png)

**Comment by maxim-saplin** [comment]
Добавил. Спасибо!
