### ISSUE TITLE
Add Results ASUS VivoBook S14

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/xOPS-App#12]
**Model:** M433IA-EB885T
**Year:** 2021?
**CPU:** AMD Ryzen 5, 4500U

**System:** Windows 10 21H1 x64
**Program version:** xOPS-Portable 1.1.2

<img width="300" alt="Снимок экрана 2021-08-30 235633" src="https://user-images.githubusercontent.com/36500228/132330305-2801ae93-7e1c-4c65-a79e-d13cf7b8b9ed.png">

**Comment by maxim-saplin** [comment]
Added
