### ISSUE TITLE
Add Results Redmi 9T

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/xOPS-App#13]
**Model:** ?
**Year:** 2021
**CPU:** Qualcomm Snapdragon 662

**API:** ?
**System:** Android 10, MIUI 12.0.5.0
**Program version:** xOPS 1.1.3

![Screenshot_2021-09-24-20-52-39-179_xcom saplin xOPS](https://user-images.githubusercontent.com/36500228/134785692-9f1e27d0-483c-4fed-8879-aa3e3504ed7d.jpg)

**Comment by maxim-saplin** [comment]
Added
