### ISSUE TITLE
Add Huawei MediaPad T3 8.0

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/xOPS-App#14]
**Model:** KOB-L09
**Year:** 2017?
**CPU:** Qualcomm Snapdragon 425

**API:** ?
**System:** Android 7, EMUI 5.1.3 (KOB-L09C170B280)
**Program version:** xOPS 1.1.3

![Screenshot_20210924-203615](https://user-images.githubusercontent.com/36500228/134967200-85ba8c35-db74-4b04-9cab-991d4a4ebac3.png)

**Comment by maxim-saplin** [comment]
Added

**Comment by maxim-saplin** [comment]
Спасибо! С наступающим!
