### ISSUE TITLE
Add Results Xiaomi Mi 10 Lite 5G

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/xOPS-App#2]
Xiaomi Mi 10 Lite 5G
(M2002J9G)
2020, Snapdragon 765G, 6/128 GB
MIUI 12.0.1 (Android 10)
![image](https://user-images.githubusercontent.com/36500228/90632905-d39e6400-e22d-11ea-8149-19baec841a0e.png)

**Comment by maxim-saplin** [comment]
Could you please make 3 runs with default Options

**Comment by KovalevArtem** [comment]
![image](https://user-images.githubusercontent.com/36500228/90676836-395a1280-e265-11ea-8c79-646ab9cf148d.png)

**Comment by maxim-saplin** [comment]
Добавил
