### ISSUE TITLE
Add Results HP 15-db1070ur

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/xOPS-App#3]
**Model:** HP 15-db1070ur
**Year:** 2019
**CPU:** AMD Ryzen 3 3200U

**System:** Windows 10 20H2 x64
**Program version:** xOPS-Portable 1.1.2

![Снимок экрана 2021-01-18 140819](https://user-images.githubusercontent.com/36500228/105533454-3922df00-5cfd-11eb-8a2d-cacbf85e62ac.png)

**Comment by maxim-saplin** [comment]
Спасибо!
