### ISSUE TITLE
Add Results POCO M3

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/xOPS-App#4]
**Model:** M2010J19CG
**Year:** 2020
**CPU:** Snapdragon 662

**System:** Android 10, MIUI 12.0.4
**Program version:** xOPS 1.1.3

![Screenshot_2021-02-27-22-48-44-513_xcom saplin xOPS](https://user-images.githubusercontent.com/36500228/109399196-6f81f880-7952-11eb-9846-b81044f005df.jpg)

![xOPS](https://user-images.githubusercontent.com/36500228/109399201-79a3f700-7952-11eb-9474-b193d44fcb31.png)

**Comment by maxim-saplin** [comment]
Добавил, спасибо!

**Comment by KovalevArtem** [comment]
@maxim-saplin 
![image](https://user-images.githubusercontent.com/36500228/113523016-e3489e00-95ad-11eb-8a52-9b7781cdb0bf.png)
POCO **M**3
