### ISSUE TITLE
Add Results Lenovo A536

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/xOPS-App#9]
**Model:** A536
**Year:** 2014
**CPU:** MediaTek MT6582

**API:** 19
**System:** Android 4.4.2, A536_S186_150813_ROW
**Program version:** xOPS 1.1.3

![Screenshot_2021-05-10-14-22-53](https://user-images.githubusercontent.com/36500228/117878211-2fbe8200-b2ae-11eb-85b2-e637ba0bac8f.png)

**Comment by maxim-saplin** [comment]
Спасибо! Добавил все результаты
